# Generated by Django 5.0.7 on 2024-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('status', models.CharField(choices=[('Onboarded', 'Onboarded'), ('Not Onboarded', 'Not Onboarded')], max_length=23)),
                ('project_Domain', models.CharField(choices=[('SAAS', 'SAAS'), ('Ecommerce', 'Ecommerce'), ('CRM', 'CRM'), ('ERP', 'ERP'), ('Finance', 'Finance')], max_length=23)),
            ],
        ),
    ]
